
name: webex_examples_releases

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tag_name: '1.1'
          prerelease: false

  


